services:
  postgres:
    image: citusdata/pg_auto_failover:latest
    container_name: postgres
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PG_AUTOCTL_HBA_LAN=true
      - PG_AUTOCTL_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
    command: >
      bash -c "
        sleep 15 &&
        pg_autoctl create postgres 
        --pgdata /var/lib/postgresql/data/postgres 
        --pgport 5432
        --username postgres 
        --dbname appdb 
        --hostname postgres 
        --auth trust 
        --monitor postgres://autoctl_node@10.164.32.93:5432/pg_auto_failover 
        --run
      "
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

volumes:
  postgres_data:

